Feat/Mobile version
alekseevgeorgy/airbnb-demo-frontend pull request #1
Opened 2017-11-10 06:37 UTC by alekseevgeorgy

2017-11-10 15:23 UTC, imevro requested changes

2017-11-10 15:23 UTC, evgenyrodionov commented on public/manifest.json
> +  "short_name": "React App",
смение название

2017-11-10 15:23 UTC, evgenyrodionov commented on src/App.css
> +  src: url(./fonts/Circular_Air-Book.woff);
расставь font weight

2017-11-10 15:23 UTC, evgenyrodionov commented on src/App.js
> +import List from "./List";
лишняя прокладка

2017-11-10 15:23 UTC, evgenyrodionov commented on src/List/Experiences/Card.js
> +//     return { star };
выкинь мусор

2017-11-10 15:23 UTC, evgenyrodionov commented on src/List/Experiences/index.js
> +            reviews="46"
числа нужно передавать числом

2017-11-10 15:23 UTC, evgenyrodionov commented on src/List/Explore/index.js
> +  <div>
а зачем этот див

2017-11-10 15:23 UTC, evgenyrodionov commented on src/List/Homes/Card.js
> +const Desciption = styled.p`
поправь

2017-11-10 15:23 UTC, evgenyrodionov commented on src/List/Homes/Card.js
> +    <Desciption>Entrie house &nbsp;&middot;&nbsp; {props.beds} beds</Desciption>
Entrie?

2017-11-11 18:13 UTC, imevro requested changes

2017-11-11 18:13 UTC, evgenyrodionov commented on src/Footer.js
> +    <MediaQuery maxDeviceWidth={767}>
нет, не нужно дублировать контент! это очень плохо

2017-11-11 18:13 UTC, evgenyrodionov commented on src/Footer.js
> +    <MediaQuery maxDeviceWidth={767}>
в два раза больше сил чтобы поддерживать

2017-11-11 18:13 UTC, evgenyrodionov commented on src/Footer.js
> +          style={{ "margin-left": "0", "margin-right": "0" }}
кошмар

2017-11-11 18:13 UTC, evgenyrodionov commented on src/Footer.js
> +          style={{ "margin-left": "0", "margin-right": "0" }}
инлайновые стили зло

2017-11-11 18:13 UTC, evgenyrodionov commented on src/Footer.js
> +          style={{ "margin-left": "0", "margin-right": "0" }}
влезать в стили сетки тоже зло

2017-11-11 18:13 UTC, evgenyrodionov commented on src/Footer.js
> +          style={{ "margin-left": "0", "margin-right": "0" }}
Жора, ебаный насос

2017-11-11 18:13 UTC, evgenyrodionov commented on src/List/Homes/index.js
> +  left: 942px;
поч не right

2017-11-11 18:13 UTC, evgenyrodionov commented on src/List/Reservations/index.js
> +const Container = styled.div`
поч не фбг2

2017-11-11 18:13 UTC, evgenyrodionov commented on src/List/Reservations/index.js
> +const Arrow = styled.button`
было же уже, поч не общий компонент

2017-11-12 00:11 UTC, alekseevgeorgy commented
- Полностью переделал футер на фбг2: убрал дублирующийся контент, дропнул инлайн стили
- Вынес кнопку "see all" и стрелки в отдельный файл с UI элементами

**То, что не стал исправлять и причины:**
> поч не фбг2?

Обсудили в чате, потому что в фбг2 колонки ропятся, в моей сетке — нет. Сообщение за 12.11 в 00:13
>инлайновые стили зло

Делал, потому что у фбг2 есть автомарджины слева/справа, получалось +8пк на сторону. В чате обсудили, что это можно опустить. Сообщение за 12.11 в 00:26

2017-11-12 11:21 UTC, imevro approved these changes

2017-11-12 11:21 UTC, merged

2017-11-12 11:22 UTC, evgenyrodionov commented
В мастере пулл сделаешь